services:
  backend:
    build: backend
    networks:
      - backend
    ports:
      - 3000:3000
    develop:
      watch:
      - path: backend/package.json
        command: npm install
      - path: backend/
        action: sync
        target: home/node/app
  frontend:
    build: spotifindr
    ports:
      - 8100:8100
    develop:
      watch:
      - path: spotifindr/package.json
        command: npm install
      - path: spotifindr/
        action: sync
        target: home/node/frontend

networks:
  backend: